hatena/renovate-config

- groupAndroidPackages.json
https://github.com/square/moshi
> Add Moshi to groupAndroidPackages

- default.json
- https://github.com/boto/boto3
- https://github.com/boto/botocore
> Group boto3 and botocore

- groupCocoaPodsPackages.json
- https://github.com/ReactiveCocoa/ReactiveSwift
- https://github.com/ReactiveCocoa/ReactiveCocoa
- https://github.com/ReactiveCocoa/ReactiveObjC
- https://github.com/ReactiveCocoa/ReactiveObjCBridge
> Add ReactiveCocoa to groupCocoaPodsPackages

- .github/workflows/validate-config.yml
> Bump actions/checkout from v1 to v2

- .github/workflows/validate-config.yml
> Bump actions/cache from v1 to v2

- groupAndroidPackages.json
Add Jetpack Compose rule.
https://developer.android.com/jetpack/androidx/releases/compose
> Add Jetpack Compose package rule to groupAndroidPackages.json

- groupAndroidPackages.json
- https://www.apollographql.com/docs/android/
- https://github.com/apollographql/apollo-android
> Add Apollo Android to groupAndroidPackages

- README.md
- automergeTypesMinor.json
- default.json
- groupAndroidPackages.json
- groupCocoaPodsPackages.json
- groupJest.json
- groupLinters.json
https://togithub.com/renovatebot/renovate/pull/6939
> Migrate packageRules selectors to new ones

- groupAndroidPackages.json
https://github.com/chrisbanes/accompanist
> Add Accompanist to groupAndroidPackages

- groupAndroidPackages.json
Hilt is now stable!
https://github.com/google/dagger/releases/tag/dagger-2.35
> Add Hilt to Dagger group

- groupAndroidPackages.json
> Add Spek to groupAndroidPackages

- groupAndroidPackages.json
https://search.maven.org/search?q=g:io.coil-kt
> Add Coil to groupAndroidPackages

- groupAndroidPackages.json
https://github.com/mannodermaus/android-junit5
> Add android-junit5 to groupAndroidPackages

- groupAndroidPackages.json
https://www.apollographql.com/docs/android/v3/
> Add `com.apollographql.apollo3` to `Apollo Android` gruop

- .github/workflows/validate-config.yml
- groupAndroidPackages.json
Flipper is tend to crash on runtime when updated.
> [Android] Disable Flipper automerge

- cpanfile.json5
https://docs.renovatebot.com/modules/versioning/#perl-versioning
> [cpanfile] Use `perl` versioning

- groupAndroidPackages.json
https://firebase.google.com/support/release-notes/android
> [Android] Add link to Firebase changelog

- cpanfile.json5
https://docs.renovatebot.com/modules/datasource/#cpan-datasource
> [cpanfile] Use `cpan` datasource

- cpanfile.json5
> [cpanfile] Ignore XML::Liberal 1.0.0

- groupAndroidPackages.json
https://docs.renovatebot.com/configuration-options/#suppress-branchpr-creation-for-x-days
ref: #57
> [Android] Add `"internalChecksFilter": "strict"` config for Firebase Android

- groupAndroidPackages.json
https://developer.android.com/jetpack/androidx/releases/compose-material3
> [Android] Add androidx.compose.material3 grouping

- groupAndroidPackages.json
> [Android] Add KSP grouping

- cpanfile.json5
https://metacpan.org/dist/HTTP-Message
> [cpanfile] Update HTTP-Message grouping

- groupAndroidPackages.json
- I want to grouping `com.airbnb.android:lottie:` and `com.airbnb.android:lottie-compose:`.
> Added android lottie grouping

- cpanfile.json5
https://metacpan.org/dist/Email-Sender
> [cpanfile] Group Email-Sender

- groupAndroidPackages.json
https://plugins.gradle.org/plugin/com.apollographql.apollo3
> [Android] Add `com.apollographql.apollo3` plugin to Apollo Android group

- README.md
- ecspressoVersion.json5
This updates `.ecspresso-version` using `regexManagers`.
> Add ecspressoVersion preset

- cpanfile.json5
- https://docs.renovatebot.com/modules/manager/cpanfile/
- https://github.com/renovatebot/renovate/pull/21152
regex manager is no longer needed 😄
> [cpanfile] Use the official cpanfile manager

- README.md
- xcodegenSwiftPackages.json5
- https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#swift-package
- https://speakerdeck.com/ikesyo/renovateniyoruiosraiburarifalsezi-dong-geng-xin?slide=19
> [iOS] Support updating Swift packages in XcodeGen's `project.yml`

- xcodegenSwiftPackages.json5
- https://docs.renovatebot.com/configuration-options/#extractversion
- https://docs.renovatebot.com/configuration-options/#extractversiontemplate
> [XcodeGen] Add extractVersionTemplate for removing v-prefix

- xcodegenSwiftPackages.json5
- https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#include
- https://github.com/search?q=path%3Axcodegen%2F**%2F*.yml&type=code
> [XcodeGen] Support splitted spec files in XcodeGen or xcodegen directory

- README.md
- ecspressoVersion.json5
- limitDockerNodeUpdatesToLTS.json5
- xcodegenSwiftPackages.json5
- https://docs.renovatebot.com/configuration-options/#custommanagers
> Rename regexManagers to customManagers

- cpanfile.json5
Test2-Suite distribution is integrated into Test-Simple distribution.
https://metacpan.org/dist/Test-Simple
> Integrate Perl Test2-Suite distribution into Test-Simple distribution
